language: go
go:
  - 1.5
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq nodejs npm
  - sudo npm install -g webpack
  - npm install
script:
  - go get -v
  - go test -v ./...
after_success:
  - bash -c "$(curl -fsSL http://bitly.com/gorelease)" gorelease
